### PR TITLE
Fixed compatibility with shvl >= 1.3.0

### LINKED ISSUE #133: "export 'default' (imported as 'shvl') was not found in 'shvl'
**Do you want to request a *feature* or report a *bug*?**
Bug 
**What is the current behavior?**
"export 'default' (imported as 'shvl') was not found in 'shvl'
**If the current behavior is a bug, please provide the steps to reproduce.**
I have installed "vuex-persistedstate": "^2.5.1",  , using webpack when I tried to compile  I got this error 

screen shot 2018-04-09 at 6 14 35 pm

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

### PR DESCRIPTION
**Pull request by qkdreyer**
Fixes #133

### CODE REVIEW

**Comment by qkdreyer** [comment]
This is a breaking change, could you merge it ASAP please ?

**Comment by brianirish** [comment]
+1, broke my app this morning when I upgraded npm deps. Downgrading shvl down to 1.2.1 works as a workaround.

Temporary workaround to downgrade shvl:
```
rm -rf node_modules/shvl
npm i --no-save shvl@1.2.1
```

**Comment by andrew-mark** [comment]
Can this be merged asap. thanks

**Comment by robinvdvleuten** [comment]
please see release v2.5.2

**Comment by yourivandenbrand** [comment]
Temporary fixed by running `npm install shvl@1.2.1` which creates a package-lock file. Run `npm shrinkwrap` which replaces package-lock with a shrinkwrap.json. Commit this and use with deployment. Shrinkwrap doesn't get updated when running 'npm install'.

**Pull request merged**
