### PR TITLE
Fix releases link

### PR DESCRIPTION
**Pull request by peschee**
**What**: Broken link fix

**Why**: Well, because it's broken :)

**How**: Add the right repo name.

**Checklist**:

- [x] Documentation
- [ ] Tests
- [x] Ready to be merged
      
- [ ] Added myself to contributors table

### CODE REVIEW

**Comment by robinvdvleuten** [comment]
Oops! Thanks @peschee!

**Comment by peschee** [comment]
👍

**Comment by robinvdvleuten** [comment]
@all-contributors add @peschee for code

**Comment by robinvdvleuten** [comment]
@all-contributors add @peschee for doc

**Comment by robinvdvleuten** [comment]
@all-contributors add @peschee for doc

**Pull request merged**
