### PR TITLE
Return error details

### PR DESCRIPTION
**Pull request by gangsthub**
We could be facing a DOMException like `QuotaExceededError`. The library was returning `Invalid storage instance given` which wasn't correct

**What**:

This will report exact error, instead of a generic one.

**Why**:

I was getting `Invalid storage instance given` when really it was a quota limit exceeded in Firefox.

**How**:

**Checklist**:

- [x] Documentation
- [x] Tests
- [ ] Ready to be merged
      
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by robinvdvleuten** [comment]
Thanks for the PR! I agree with you that the error should be more precise about why the storage cannot be written. But just rethrowing within a try/catch feels a bit weird. Could you make some changes related to my feedback?

**Comment by robinvdvleuten** [comment]
Even better would be to make it also configurable to through options;

```js
shvl.get(options, "assertStorage", assertStorage)(storage);
```

**Comment by gangsthub** [comment]
> ```js
> shvl.get(options, "assertStorage", assertStorage)(storage);
> ```

Any function? That could modify the behavior of the whole module 😅.

>  just rethrowing within a try/catch feels a bit weird

You're right, `throw`ing inside a `catch` is a little bit harsh.

Another thing: with both your solution and mine, the whole package could throw an error and crash the app before initializing. I think I'll follow your guidelines but I'll add a `console.error` in a `catch` in case it fails to instantiate.

**Comment by robinvdvleuten** [comment]
@gangsthub an error is thrown nonetheless by the plugin when the check fails (https://github.com/robinvdvleuten/vuex-persistedstate/blob/master/index.js#L52). It would improve the DX if it is the actual error instead of a generic one.

**Comment by gangsthub** [comment]
Sorry, I added some commits that weren't mine, so I opened a new PR with your suggestions: #252.

**Pull request closed without merging**
